apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-role-binding
  namespace: agents
subjects:
- kind: ServiceAccount
  name: default  # Or specify a custom service account
  namespace: agents
roleRef:
  kind: Role
  name: secret-access-role #binding this role to specified service account above.
  apiGroup: rbac.authorization.k8s.io